<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1I7HGI1" failures="2" tests="4" name="OneTime_Payment" time="83.789" errors="0" timestamp="2024-01-25T17:47:47 IST">
  <testcase classname="package_Test.OneTime_Wallet_payment" name="walletTest" time="8.89"/>
  <testcase classname="package_Test.OneTime_Card_payment" name="cardTest" time="9.34">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [PASS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [PASS] but found [FAIL]
at package_Test.OneTime_Card_payment.cardTest(OneTime_Card_payment.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- cardTest -->
  <testcase classname="package_Test.OneTime_NetBanking_payment" name="Netbanking" time="8.13">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [PASS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [PASS] but found [FAIL]
at package_Test.OneTime_NetBanking_payment.Netbanking(OneTime_NetBanking_payment.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Netbanking -->
  <testcase classname="package_Test.OneTime_UPI_payment" name="UPITest" time="17.262"/>
</testsuite> <!-- OneTime_Payment -->
